/* 
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using locationiq.Api;
using locationiq.Model;
using locationiq.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace locationiq.Test
{
    /// <summary>
    ///  Class for testing Address
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AddressTests
    {
        // TODO uncomment below to declare an instance variable for Address
        //private Address instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Address
            //instance = new Address();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Address
        /// </summary>
        [Test]
        public void AddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Address
            //Assert.IsInstanceOfType<Address> (instance, "variable 'instance' is a Address");
        }


        /// <summary>
        /// Test the property 'HouseNumber'
        /// </summary>
        [Test]
        public void HouseNumberTest()
        {
            // TODO unit test for the property 'HouseNumber'
        }
        /// <summary>
        /// Test the property 'Road'
        /// </summary>
        [Test]
        public void RoadTest()
        {
            // TODO unit test for the property 'Road'
        }
        /// <summary>
        /// Test the property 'Residential'
        /// </summary>
        [Test]
        public void ResidentialTest()
        {
            // TODO unit test for the property 'Residential'
        }
        /// <summary>
        /// Test the property 'Village'
        /// </summary>
        [Test]
        public void VillageTest()
        {
            // TODO unit test for the property 'Village'
        }
        /// <summary>
        /// Test the property 'County'
        /// </summary>
        [Test]
        public void CountyTest()
        {
            // TODO unit test for the property 'County'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Test]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

    }

}
