/* 
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using locationiq.Api;
using locationiq.Model;
using locationiq.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace locationiq.Test
{
    /// <summary>
    ///  Class for testing DirectionsMatrix
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DirectionsMatrixTests
    {
        // TODO uncomment below to declare an instance variable for DirectionsMatrix
        //private DirectionsMatrix instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DirectionsMatrix
            //instance = new DirectionsMatrix();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DirectionsMatrix
        /// </summary>
        [Test]
        public void DirectionsMatrixInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DirectionsMatrix
            //Assert.IsInstanceOf(typeof(DirectionsMatrix), instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Distances'
        /// </summary>
        [Test]
        public void DistancesTest()
        {
            // TODO unit test for the property 'Distances'
        }
        /// <summary>
        /// Test the property 'FallbackSpeedCells'
        /// </summary>
        [Test]
        public void FallbackSpeedCellsTest()
        {
            // TODO unit test for the property 'FallbackSpeedCells'
        }
        /// <summary>
        /// Test the property 'Sources'
        /// </summary>
        [Test]
        public void SourcesTest()
        {
            // TODO unit test for the property 'Sources'
        }
        /// <summary>
        /// Test the property 'Destinations'
        /// </summary>
        [Test]
        public void DestinationsTest()
        {
            // TODO unit test for the property 'Destinations'
        }

    }

}
