/* 
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using locationiq.Api;
using locationiq.Model;
using locationiq.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace locationiq.Test
{
    /// <summary>
    ///  Class for testing Location
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocationTests
    {
        // TODO uncomment below to declare an instance variable for Location
        //private Location instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Location
            //instance = new Location();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Location
        /// </summary>
        [Test]
        public void LocationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Location
            //Assert.IsInstanceOf(typeof(Location), instance);
        }


        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'PlaceId'
        /// </summary>
        [Test]
        public void PlaceIdTest()
        {
            // TODO unit test for the property 'PlaceId'
        }
        /// <summary>
        /// Test the property 'Licence'
        /// </summary>
        [Test]
        public void LicenceTest()
        {
            // TODO unit test for the property 'Licence'
        }
        /// <summary>
        /// Test the property 'OsmType'
        /// </summary>
        [Test]
        public void OsmTypeTest()
        {
            // TODO unit test for the property 'OsmType'
        }
        /// <summary>
        /// Test the property 'OsmId'
        /// </summary>
        [Test]
        public void OsmIdTest()
        {
            // TODO unit test for the property 'OsmId'
        }
        /// <summary>
        /// Test the property 'Boundingbox'
        /// </summary>
        [Test]
        public void BoundingboxTest()
        {
            // TODO unit test for the property 'Boundingbox'
        }
        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Test]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }
        /// <summary>
        /// Test the property 'Lon'
        /// </summary>
        [Test]
        public void LonTest()
        {
            // TODO unit test for the property 'Lon'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Class'
        /// </summary>
        [Test]
        public void ClassTest()
        {
            // TODO unit test for the property 'Class'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Importance'
        /// </summary>
        [Test]
        public void ImportanceTest()
        {
            // TODO unit test for the property 'Importance'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Namedetails'
        /// </summary>
        [Test]
        public void NamedetailsTest()
        {
            // TODO unit test for the property 'Namedetails'
        }
        /// <summary>
        /// Test the property 'Matchquality'
        /// </summary>
        [Test]
        public void MatchqualityTest()
        {
            // TODO unit test for the property 'Matchquality'
        }

    }

}
