/* 
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using locationiq.Client;
using locationiq.Api;
using locationiq.Model;

namespace locationiq.Test
{
    /// <summary>
    ///  Class for testing BalanceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BalanceApiTests
    {
        private BalanceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BalanceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BalanceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BalanceApi
            //Assert.IsInstanceOfType(typeof(BalanceApi), instance, "instance is a BalanceApi");
        }

        
        /// <summary>
        /// Test Balance
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Balance();
            //Assert.IsInstanceOf<Balance> (response, "response is Balance");
        }
        
    }

}
