/* 
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Address
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressTests
    {
        // TODO uncomment below to declare an instance variable for Address
        //private Address instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Address
            //instance = new Address();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Address
        /// </summary>
        [Test]
        public void AddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Address
            //Assert.IsInstanceOf(typeof(Address), instance);
        }


        /// <summary>
        /// Test the property 'HouseNumber'
        /// </summary>
        [Test]
        public void HouseNumberTest()
        {
            // TODO unit test for the property 'HouseNumber'
        }
        /// <summary>
        /// Test the property 'Road'
        /// </summary>
        [Test]
        public void RoadTest()
        {
            // TODO unit test for the property 'Road'
        }
        /// <summary>
        /// Test the property 'Residential'
        /// </summary>
        [Test]
        public void ResidentialTest()
        {
            // TODO unit test for the property 'Residential'
        }
        /// <summary>
        /// Test the property 'Borough'
        /// </summary>
        [Test]
        public void BoroughTest()
        {
            // TODO unit test for the property 'Borough'
        }
        /// <summary>
        /// Test the property 'Neighbourhood'
        /// </summary>
        [Test]
        public void NeighbourhoodTest()
        {
            // TODO unit test for the property 'Neighbourhood'
        }
        /// <summary>
        /// Test the property 'Quarter'
        /// </summary>
        [Test]
        public void QuarterTest()
        {
            // TODO unit test for the property 'Quarter'
        }
        /// <summary>
        /// Test the property 'Hamlet'
        /// </summary>
        [Test]
        public void HamletTest()
        {
            // TODO unit test for the property 'Hamlet'
        }
        /// <summary>
        /// Test the property 'Suburb'
        /// </summary>
        [Test]
        public void SuburbTest()
        {
            // TODO unit test for the property 'Suburb'
        }
        /// <summary>
        /// Test the property 'Island'
        /// </summary>
        [Test]
        public void IslandTest()
        {
            // TODO unit test for the property 'Island'
        }
        /// <summary>
        /// Test the property 'Village'
        /// </summary>
        [Test]
        public void VillageTest()
        {
            // TODO unit test for the property 'Village'
        }
        /// <summary>
        /// Test the property 'Town'
        /// </summary>
        [Test]
        public void TownTest()
        {
            // TODO unit test for the property 'Town'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'CityDistrict'
        /// </summary>
        [Test]
        public void CityDistrictTest()
        {
            // TODO unit test for the property 'CityDistrict'
        }
        /// <summary>
        /// Test the property 'County'
        /// </summary>
        [Test]
        public void CountyTest()
        {
            // TODO unit test for the property 'County'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'StateDistrict'
        /// </summary>
        [Test]
        public void StateDistrictTest()
        {
            // TODO unit test for the property 'StateDistrict'
        }
        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Test]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'StateCode'
        /// </summary>
        [Test]
        public void StateCodeTest()
        {
            // TODO unit test for the property 'StateCode'
        }

    }

}
