/* 
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing DirectionsDirectionsRoutes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DirectionsDirectionsRoutesTests
    {
        // TODO uncomment below to declare an instance variable for DirectionsDirectionsRoutes
        //private DirectionsDirectionsRoutes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DirectionsDirectionsRoutes
            //instance = new DirectionsDirectionsRoutes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DirectionsDirectionsRoutes
        /// </summary>
        [Test]
        public void DirectionsDirectionsRoutesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DirectionsDirectionsRoutes
            //Assert.IsInstanceOf(typeof(DirectionsDirectionsRoutes), instance);
        }


        /// <summary>
        /// Test the property 'Legs'
        /// </summary>
        [Test]
        public void LegsTest()
        {
            // TODO unit test for the property 'Legs'
        }
        /// <summary>
        /// Test the property 'WeightName'
        /// </summary>
        [Test]
        public void WeightNameTest()
        {
            // TODO unit test for the property 'WeightName'
        }
        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Test]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

    }

}
