/* 
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing DirectionsMatching
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DirectionsMatchingTests
    {
        // TODO uncomment below to declare an instance variable for DirectionsMatching
        //private DirectionsMatching instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DirectionsMatching
            //instance = new DirectionsMatching();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DirectionsMatching
        /// </summary>
        [Test]
        public void DirectionsMatchingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DirectionsMatching
            //Assert.IsInstanceOf(typeof(DirectionsMatching), instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Tracepoints'
        /// </summary>
        [Test]
        public void TracepointsTest()
        {
            // TODO unit test for the property 'Tracepoints'
        }
        /// <summary>
        /// Test the property 'Matchings'
        /// </summary>
        [Test]
        public void MatchingsTest()
        {
            // TODO unit test for the property 'Matchings'
        }

    }

}
